#!/usr/bin/env node
/**
 * Writes apps/*\/.env.local from the LOCAL Supabase stack.
 *
 * CI has no .env.local, and `next build` bakes NEXT_PUBLIC_* into .next/**,
 * so the values must exist before the build — not just before the tests.
 *
 * Never writes SECRET_KEY: it has BYPASSRLS, and both EXPO_PUBLIC_* and
 * NEXT_PUBLIC_* are inlined into shipped bundles.
 *
 * Run: yarn env:local [--force]
 */
import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const REPO_ROOT = path.resolve(import.meta.dirname, '..');
const force = process.argv.includes('--force');

function readStatus() {
  const out = execFileSync('yarn', ['supabase', 'status', '-o', 'env'], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
  });
  const get = (key) => out.match(new RegExp(`^${key}="(.*)"$`, 'm'))?.[1];
  // The CLI renamed ANON_KEY -> PUBLISHABLE_KEY; accept either.
  return { url: get('API_URL'), key: get('PUBLISHABLE_KEY') ?? get('ANON_KEY') };
}

const { url, key } = readStatus();

if (!url || !key) {
  console.error('Could not read local Supabase status. Is `yarn db:start` running?');
  process.exit(1);
}

// Same hard guard as scripts/seed-auth.mjs.
if (!/^https?:\/\/(127\.0\.0\.1|localhost)(:|\/|$)/.test(url)) {
  console.error(`Refusing to write env for a non-local URL: ${url}`);
  process.exit(1);
}

const SITE_URL = 'http://localhost:3000';

const FILES = [
  {
    file: 'apps/web/.env.local',
    body: [
      '# Generated by `yarn env:local`. Safe to edit; re-run with --force to reset.',
      `NEXT_PUBLIC_SUPABASE_URL=${url}`,
      `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${key}`,
      `NEXT_PUBLIC_SITE_URL=${SITE_URL}`,
    ],
  },
  {
    file: 'apps/native/.env.local',
    body: [
      '# Generated by `yarn env:local`. Safe to edit; re-run with --force to reset.',
      `EXPO_PUBLIC_SUPABASE_URL=${url}`,
      `EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${key}`,
      '# iOS simulator. Android emulator: http://10.0.2.2:3000. Device: your LAN IP.',
      `EXPO_PUBLIC_API_URL=${SITE_URL}`,
    ],
  },
];

for (const { file, body } of FILES) {
  const target = path.join(REPO_ROOT, file);
  if (existsSync(target) && !force) {
    console.log(`skip   ${file} (exists — pass --force to overwrite)`);
    continue;
  }
  writeFileSync(target, `${body.join('\n')}\n`);
  console.log(`write  ${file}`);
}
