// Adds `className` to React Native's core components. apps/native has its own
// copy (generated by the Metro plugin); this package needs one too, because it
// typechecks independently of any app.
/// <reference types="react-native-css/types" />
